### ISSUE TITLE
is this project ready for product use?

### ISSUE THREAD

**Issue by hongjundu** [VolantMQ/volantmq#105]
I am looking for a go version mqtt broker, seems this one is most active.

Thanks

**Comment by SantoshSah** [comment]
Any update?

**Comment by troian** [comment]
Yes

**Comment by SantoshSah** [comment]
Thank you. I will try it. Is there any documentation that explains how to use it?

**Comment by gilfrade** [comment]
Do you know who uses voltantMQ? Any enterprise?

**Comment by troian** [comment]
We use it on our prod servers but still don't have any feedback from out unfortunately

**Comment by gilfrade** [comment]
Can you clarify more your specific use case? How many servers, how many connections per second, messages per second, for example.
