### ISSUE TITLE
Where is the persistence repo ?

### ISSUE THREAD

**Issue by LovelyLich** [VolantMQ/volantmq#107]
I have used the VolantMQ/persistence in my project before, but today when i try to clone this repo again , i tell me 404 not found. where is it now ?

**Comment by troian** [comment]
It's moved
https://github.com/VolantMQ/vlapi/tree/master/plugin/persistence

**Comment by LovelyLich** [comment]
So, and where is the examples for how to use volantmq. before, there are some examples named like: 
tcpBoltDB、tcpInMem and so on. thanks for your reply.

**Comment by troian** [comment]
Just use docker image mentioned [here](https://github.com/VolantMQ/volantmq#how-to-use)
