### ISSUE TITLE
Wrong definition it yaml config naming

### ISSUE THREAD

**Issue by janderssen** [VolantMQ/volantmq#110]
Hi,

Just working on getting VolantMQ up and running, was having an issue with the default out of the box build, worked out that the Auth Config Order has wrong name :  
was
Order     []string `yaml:"order"`

Should be I think from the default config.
Order     []string `yaml:"defaultOrder"`

I hope this helps, and is correct.

Cheers
Jason

**Comment by yqylovy** [comment]
Same error, add a pull to fix it [pull-112](https://github.com/VolantMQ/volantmq/pull/112).

**Comment by troian** [comment]
Merged
