### ISSUE TITLE
Consider use service as library

### ISSUE THREAD

**Issue by troian** [VolantMQ/volantmq#115]
There are couple of requests to use this project as a library which seems quite reasonable.
Besides plugins everything seems to be ok

**Comment by bc547** [comment]
Are there any guidelines on how to use volantmq as an embedded library in a larger project?

**Comment by troian** [comment]
Have not managed to implement this yet unfortunately.

**Comment by maddie** [comment]
Any plans for this to be implemented? I'm very interested in embedding this project as library into our current project too.

**Comment by troian** [comment]
You can try it now though. Executable is moved to `cmd/volantmq` thus you can embed.
Just use cmd as a reference.
Let me know in case its not working
