### ISSUE TITLE
Builds for armhf

### ISSUE THREAD

**Issue by DamiaPoquet** [VolantMQ/volantmq#116]
It should be awesome to build VolantMQ for another architectures like armhf, so we can use it in a Raspberry Pi. 

Also, build a Docker image for armhf.

Really appreciate it. :)

**Comment by troian** [comment]
Is **arm64** suitable?
https://github.com/golang/go/wiki/GoArm

**Comment by DamiaPoquet** [comment]
For Raspberry Pi it must be built for armhf (GOARCH=arm), but other devices can take profit of arm64.

**Comment by troian** [comment]
Looks like not a quick task unfortunately. If you have a time to work on PR is welcome
