### ISSUE TITLE
flow quota concurrency

### ISSUE THREAD

**Issue by yqylovy** [VolantMQ/volantmq#121]
Please fill out the sections below to help us address your issue.

### Version of VolantMQ (or SHA)

master

### Version of Go (`go version`)?

go1.11

### What issue did you see?

flow.quota may <0 when goroutine `Load` at a same time .

### Steps to reproduce

```
func main() {
	a := int32(1)
	for i := 0; i < 2; i++ {
		go func(name string) {
			if atomic.LoadInt32(&a) == 0 {
				fmt.Printf("%v load zero and return\n", name)
			}
			time.Sleep(time.Second * 1)
			got := atomic.AddInt32(&a, -1)
			fmt.Printf("%v current a:%v\n", name, got)
		}(fmt.Sprintf("runner-%d", i))
	}
	time.Sleep(time.Second * 3)
}
```

**Comment by troian** [comment]
Checking to -1 is wrong. Once again, if that happens there is some design bug in the code.
Any panics etc in the code use? How you did you catch this bug?

**Comment by yqylovy** [comment]
As show in example code, Load-Check-Add is no thread safe.Some change may happen between two operation.It rarely happen and hard to catch. So I add `sleep` between it to make it easier to observe.

If don't want to add then reduce, you can Load-check-CompareAndSet to make sure no change happened.
