### ISSUE TITLE
Found two mistakes

### ISSUE THREAD

**Issue by emmm23333** [VolantMQ/volantmq#127]
1. In sessions.go, when writing session properties
```
resp.PropertySet(mqttp.PropertyServerKeepAlive,m.KeepAlive)
```
I think it's right to replace m.KeepAlive with uint16(m.KeepAlive.Period) ? 

2. In property.go, maybe it's right to add CONNACK to PropertySessionExpiryInterval according   to MQTT5.0 protocol?

**Comment by troian** [comment]
resolved
