### ISSUE TITLE
Can not build project, vlapi folder names are changed

### ISSUE THREAD

**Issue by ZeoX06** [VolantMQ/volantmq#130]
### Version of VolantMQ (or SHA)
master and v0.2.5

### Version of Go (`go version`)?
go1.11.1 linux/amd64

### What issue did you see?
Changes of vlapi effecting building of volantmq.

### Steps to reproduce
Run build via Dockerfile

I was not able to compile VolantMQ. If I recreate the old folder structure of the vlapi I was able to compile the project but received the following error:

server create{error 25 0  invalid argument}

**Comment by troian** [comment]
thanks, will fix in next release

**Comment by troian** [comment]
https://github.com/VolantMQ/volantmq/releases/tag/v0.3.0
