### ISSUE TITLE
what need to do with the "retained"  variable?

### ISSUE THREAD

**Issue by chenyf** [VolantMQ/volantmq#132]
Hi,   the code in clients/session.go  show as below,  you create a "retained" variable, set the QoS and topic,  but I think you need do something more with this  "retained" variable, am I right?

func (s *session) SignalPublish(pkt *mqttp.Publish) error {
    // [MQTT-3.3.1.3]
    if pkt.Retain() {
        if err := s.messenger.Retain(pkt); err != nil {
            s.log.Error("Error retaining message", zap.String("clientId", s.id), zap.Error(err))
        }   

        // [MQTT-3.3.1-7]
        if pkt.QoS() == mqttp.QoS0 {
            retained := mqttp.NewPublish(s.version)
            if err := retained.SetQoS(pkt.QoS()); err != nil {
                s.log.Error("set retained QoS", zap.String("clientId", s.id), zap.Error(err))
            }   
            if err := retained.SetTopic(pkt.Topic()); err != nil {
                s.log.Error("set retained topic", zap.String("clientId", s.id), zap.Error(err))
            }   
        }   
    }  
    ....
}

**Comment by troian** [comment]
Looks like a dead code
