### ISSUE TITLE
Do not support websocket now?

### ISSUE THREAD

**Issue by nxsre** [VolantMQ/volantmq#138]
In the history of the git:
8917796 Turn off web sockets
In the code: 
![image](https://user-images.githubusercontent.com/32614138/68660241-bf795800-0573-11ea-9616-938fb3328d91.png)

**Comment by troian** [comment]
Yes, websockets needs rework. I'll put it in a list

**Comment by troian** [comment]
@soopsio enabled in https://github.com/VolantMQ/volantmq/pull/141
