### ISSUE TITLE
Build helm chart

### ISSUE THREAD

**Issue by troian** [VolantMQ/volantmq#147]

**Comment by saikatharryc** [comment]
@troian do you have any specific repo for this? I Just wanted to know how do I contribute to this issue as I want to?

**Comment by 4nte** [comment]
I'm happy to help too @saikatharryc @troian

**Comment by troian** [comment]
@saikatharryc @4nte Thank you guys for interest. We don't have any specific repo for this task. I think you will need to fork official Helm charts repo and commit in there

**Comment by 4nte** [comment]
It's not possible to add new charts to the Helm charts repo anymore due to deprecation strategy. 

Now each organisation should host their own repo and optionally add it to the helm hub.
Luckily hosting a chart repo is pretty simple, it can be hosted via Github pages.

If you create a repo on github I can setup everything and automate it with Github actions.

**Comment by troian** [comment]
@4nte https://github.com/VolantMQ/helm is set

**Comment by saikatharryc** [comment]
@4nte once you start I can fork and contribute, at this point it doesn’t allowing me to fork.

**Comment by 4nte** [comment]
> @4nte once you start I can fork and contribute, at this point it doesn’t allowing me to fork.

Sure, I'll get something up by the end of the day.
I already have a working helm chart that we've been deploying at Spotsie.io it but it might use some polishing.

**Comment by saikatharryc** [comment]
@troian ,  @4nte  is it possible to add me as well as a collaborator to the helm repo?

and is there any slack channel or communication channel for all the volantmq contributors?
would love to join and discuss about the pending features!

**Comment by troian** [comment]
Sure. I’ll add.
There is a volantmq channel in gophers.slack.com

**Comment by saikatharryc** [comment]
> There is a volantmq channel in gophers.slack.com


@troian thank you!
to join the slack, I guess I will be needing an invitation. it's not letting me signup.

**Comment by troian** [comment]
You can join here https://invite.slack.golangbridge.org

**Comment by troian** [comment]
@4nte @saikatharryc shall we resolve it?

**Comment by saikatharryc** [comment]
we have a helm chart [here](https://github.com/VolantMQ/helm).
hence we can close the issue. (@troian I don't have the authority to close )

**Comment by troian** [comment]
oh, thanks for update. I'll close
Much appreciated your time on it!
