### ISSUE TITLE
Consider filing PR on zentures/surgemq

### ISSUE THREAD

**Issue by cameronelliott** [VolantMQ/volantmq#177]
It was only by pure luck I found your project, my google search for 'go mqtt broker' did not include this project on the first page.
It was only by luck and digging through the reddit link I found you throught the Surge fork.

I would suggest you file a PR at github.com/zentures/surgemq to see if they would forward traffic to you, 
since I believe that is your lineage.
(you might also ask if the maintainer wants to us the github archived feature)

Then users ending up at that repo won't feel like they hit a dead end, and they have an option for a go mqtt broker.

It might help the growth of your project also.

Anyway, I want to see Go MQTT brokers do well, so I hope this helps.

**Comment by troian** [comment]
Thanks for suggestion. @zhenjl is it possible to archive [surgemq](https://github.com/zentures/surgemq) and reference VolantMQ project in readme so people can be forwarded to?

**Comment by zhenjl** [comment]
Archived and added reference. Great work happening here!

**Comment by troian** [comment]
Much appreciated @zhenjl
