### ISSUE TITLE
客户端事件获取问题

### ISSUE THREAD

**Issue by jiazheng001** [VolantMQ/volantmq#179]
为什么0.4.0-rc.8通过订阅$SYS/servers//sessions/#事件获取不到客户端连接断开事件了,谢谢,麻烦解答一下!

**Comment by troian** [comment]
Not sure I understand what you wanted to tell

**Comment by jiazheng001** [comment]
> 不知道我明白你想说什么

它可以和github.com/eclipse/paho.mqtt.golang这个客户端库兼容吗?

**Comment by jiazheng001** [comment]
> 不知道我明白你想说什么

噢噢,那现在这个最新的版本支持mqtt3.1.1协议还是5.0协议
