### ISSUE TITLE
add empty Persistence provider

### ISSUE THREAD

**Issue by ddatsh** [VolantMQ/volantmq#46]
don't want persistence  anything
or if mqtt client library bug,then don't reply such as PUBCOMP,broker memory will leak?

so want a empty Persistence provider

**Comment by troian** [comment]
>> or if mqtt client library bug,then don't reply such as PUBCOMP,broker memory will leak?
Mostly like that but not so. PUBREL awaiting PUBCOMP and stays until client reconnects, or connects with clean session 1.
There is possibility to add ack timeout but it is hack

**Comment by ddatsh** [comment]
so,set ack timeout is really need
but for just test,whatever  still want empty persistence provider :)  , just not  persistence anything

**Comment by troian** [comment]
Ack timeout is not covered by spec. Better force client to reconnect with clean session 1

**Comment by ddatsh** [comment]
I know Ack timeout is not covered by spec, and surgemq will delete client persistence when client disconnect
still beg to add empty persistence  provider :)
