### ISSUE TITLE
How to support both mqtt and websocket in same broker service instance?

### ISSUE THREAD

**Issue by liaoliaopro** [VolantMQ/volantmq#52]
Listen twice with differenct ConfigTCP&ConfigWS will do?

```
go srv.ListenAndServe(config)
srv.ListenAndServe(configWs)
```
Is this the correct way?

**Comment by liaoliaopro** [comment]
elang mqtt broker FYI: https://github.com/emqtt/emqttd

**Comment by troian** [comment]
Yes, it works. You may run as many listeners as you want on save server. Event mixing up plain tcp and websocket
Check examples/tcp&ws

**Comment by liaoliaopro** [comment]
Great!
