### ISSUE TITLE
Middleware option

### ISSUE THREAD

**Issue by tebben** [VolantMQ/volantmq#60]
Is it possible to add some middleware option like in the HTTP package? For our project I need to process incoming messages before sending it to the subscribers.

**Comment by troian** [comment]
@tebben  Yeah, good idea. Can you make API proposal?
We can do then preprocess API and anyone who want can make own plugin further

**Comment by tebben** [comment]
**Introduction**
This proposal address the problem that there is curently no option to hook into the incoming messages.

**Problem**
When you're building an application using volantmq there's probably some shared functionality that you want to run for many or all incoming messages. You might want to log, store, check or do some processing before pushing the messages to the subscribers of a topic.

Volantmq curently calls publishToTopic() -> TopicMessenger.Publish() from connection.go which gives no option to do something with the incoming message before sending to the subscribers.

An example of this problem
We are building an open-source SensorThings server based on this OGC standard http://docs.opengeospatial.org/is/15-078r6/15-078r6.html
In chapter 14 the standard describes the MQTT extension we should implement for the server: User publishes a new Observation on Topic Datastreams(1)/Observations, the incoming observation needs to be checked for mandatory parameters and in some cases altered with extra information and stored in the database also adding an id to the observation. When processed the Observation should be send to all subscribers of topic Datastreams(1)/Observations.

**Proposal**
Add an option so we can implement our middleware that satisfies a function, I think it's not needed to implement something as extensive as the middleware implementation in go's HTTP package.
An option can be something simple as supplying a BeforePublish function to the server which will be called before TopicMessenger.Publish(), something like:

```
package main

func myBeforePublishHandler(clientID string, msg *packet.Publish) error {
	// do stuff here
	return nil
}

func main() {
	server := volantmq.NewServer(serverConfig)
	sever.BeforePublishHandler = myBeforePublishHandler
}
```

**Comment by troian** [comment]
MQTT V5.0 has properties thus server does some pre publish checks. If issuing of callback is fine after those checks I'll implement

**Comment by troian** [comment]
Sorry, it took a long.
VolantMQ is now supporting plugins. Just thinking how better fit it
