### ISSUE TITLE
Logger should be interface type

### ISSUE THREAD

**Issue by ipfans** [VolantMQ/volantmq#63]
Logger need more configurable with interface type. So it will be more suitable for common use.

Although we also used zap-logger in production, but we still want to spec log level or something details for logger for debug or others.

Logger Level can be:

```go
type Logger interface{
    Named(s string) Logger
    Debug(msg string, fields ...interface{})
    Info(msg string, fields ...interface{})
    Warn(msg string, fields ...interface{})
    Error(msg string, fields ...interface{}) 
    Fatal(msg string, fields ...interface{})
}
```

**Comment by troian** [comment]
@ipfans I didn't catch your thought. can you detail it please

**Comment by ipfans** [comment]
Sorry for my pool english. @troian I updated code snippet to keep clearify.

I think ```ServerConfig``` or ```Server``` should export setter method of Logger interface  to customize logger of volantmq. E.x., I want to redirect volantmq log to file or syslog.

Also I need set different level when I need debug transport and decode details.

**Comment by troian** [comment]
Gotcha. Make sense

**Comment by ipfans** [comment]
@troian another component ```persistence``` also can be interface type. It will be better than currnet implemention.

In default settings, all data store in memory without persistence. But developer can be change persistence backend by its own implemention(such as redis/influxdb/blotdb/postgresql etc.)

**Comment by troian** [comment]
That will be a bit changed. Persistence gonna be plugin based and memory implementation set as default

**Comment by ipfans** [comment]
Oh, I saw that metioned in #53 , but currently plugin system [only works on Linux](https://github.com/golang/go/issues/19282). So I think it shoud be discussed to make volantmq working on multi OS.

**Comment by troian** [comment]
I think we start with [hashicorp implementation](https://github.com/hashicorp/go-plugin). Should be multiplatform

**Comment by ipfans** [comment]
Oh, this would be nice.

**Comment by ipfans** [comment]
@troian I also have question about product positioning of VolantMQ. If VolantMQ will be a dependency server, there would be nice with plugins ecosystem to extend the ability of VolantMQ server. But as a MQTT library, I think plugin ecosystem enforce user to build/use embedded plugins, that not very friendly to developer.

**Comment by troian** [comment]
As library VolantMQ has base which is enough to start i.e. it carries all of necessary API inside.
Plugins will be mostly for daemon but developers could use them as libraries as well.
For example BoltDB persistence can be imported into project which import VolantMQ as library

**Comment by ipfans** [comment]
Gotcha. Thanks for your answer.
