### ISSUE TITLE
connection.go:217 opanic: file tcp 127.0.0.1:1883->127.0.0.1:1691: not supported by windows(VolantMQ/volantmq/connection/connection.go:217 )

### ISSUE THREAD

**Issue by longzhou3** [VolantMQ/volantmq#73]
```
func (s *Type) Start() {
	s.onStart.Do(func() {
		s.txRun()
		s.EventPoll.Start(s.Desc, s.rxRun) // nolint: errcheck
		s.started.Done()
	})
}
```

panic: file tcp 127.0.0.1:1883->127.0.0.1:1691: not supported by windows
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x710bca]

goroutine 33 [running]:
github.com/VolantMQ/volantmq/connection.(*Type).Start(0x0)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/connection/connection.go:217 +0x3a
github.com/VolantMQ/volantmq/clients.(*session).start(0xc04216e000)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/clients/session.go:142 +0x93
github.com/VolantMQ/volantmq/clients.(*Manager).NewSession.func1(0xc042177b40, 0xc04223dc48, 0xc0420ea000, 0xc042177b30, 0xc042177b28, 0xc042177b20)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/clients/sessions.go:160 +0x4b7
panic(0x891840, 0xc04265a0f0)
	E:/Go/src/runtime/panic.go:491 +0x291
github.com/troian/easygo/netpoll.Must(0x0, 0xb5d840, 0xc04265a0f0, 0xb5d840)
	E:/LzGo/volantmq/src/github.com/troian/easygo/netpoll/handle.go:41 +0x5b
github.com/VolantMQ/volantmq/clients.(*Manager).newConnectionPreConfig(0xc0420ea000, 0xc042177c48, 0x0)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/clients/sessions.go:299 +0x99
github.com/VolantMQ/volantmq/clients.(*Manager).configureSession(0xc0420ea000, 0xc042177c48, 0xc04216e000, 0xc042088060, 0x20, 0xc04216e000, 0x0, 0x0, 0x5594a0294570c68c)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/clients/sessions.go:322 +0x14c
github.com/VolantMQ/volantmq/clients.(*Manager).NewSession(0xc0420ea000, 0xc04223dc48)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/clients/sessions.go:181 +0x22c
github.com/VolantMQ/volantmq/transport.(*baseConfig).handleConnection(0xc042042000, 0xb65f20, 0xc04208a040)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/transport/base.go:147 +0xb2d
github.com/VolantMQ/volantmq/transport.(*tcp).Serve.func1(0xc042042000, 0xb660a0, 0xc042162000)
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/transport/tcp.go:136 +0xfb
created by github.com/VolantMQ/volantmq/transport.(*tcp).Serve
	E:/LzGo/volantmq/src/github.com/VolantMQ/volantmq/transport/tcp.go:130 +0xda

**Comment by troian** [comment]
Windows not planned to support. Please use Docker image
