### ISSUE TITLE
this line should be “esle if h.mType == PUBLISH”?

### ISSUE THREAD

**Issue by hawklin2017** [VolantMQ/volantmq#75]
https://github.com/VolantMQ/volantmq/blob/34d2e1ee4904559aafe37890ca9df5f40d8e14f3/packet/header.go#L236
i think，case as that CONNECT with invalid Flag，such as QOS=1，this is not rejected。

**Comment by troian** [comment]
CONNECT with invalid flags is handled here 
```
h.mType != PUBLISH && h.mFlags != h.mType.DefaultFlags()
```
