### ISSUE TITLE
build fail on windows

### ISSUE THREAD

**Issue by sjatsh** [VolantMQ/volantmq#78]
github.com\troian\easygo\netpoll\handle.go:97:38: cannot use desc.fd() (type int) as type syscall.Handle in argument to syscall.SetNonblock

**Comment by troian** [comment]
I'm not sure it supposed to work on Windows as I never done any tests on that system. More over netpoll is designed to work either with epoll or kqueue on Linux and Unix respectively and I have no clue how such things done on Windowns. I'll close this in favor of #79 as running on Windows requires more complex work

**Comment by sjatsh** [comment]
thanks
