### ISSUE TITLE
is there any way to get the publish message in server side without subscribe?

### ISSUE THREAD

**Issue by xurwxj** [VolantMQ/volantmq#85]
is there any way to get the publish message in server side without subscribe?
i want to save the publish message to db in volantmq server

**Comment by troian** [comment]
Not yet but planned over plugins

**Comment by xurwxj** [comment]
can we get messages through plugin now?

**Comment by xurwxj** [comment]
add a interface func in types.go:
```
type Packets interface {
	PacketCountQoS0([]byte) (int, error)
	PacketCountQoS12([]byte) (int, error)
	PacketCountUnAck([]byte) (int, error)
	PacketStoreQoS0([]byte, *PersistedPacket) error
	PacketStoreQoS12([]byte, *PersistedPacket) error
	PacketsForEachQoS0([]byte, interface{}, PacketLoader) error
	PacketsForEachQoS12([]byte, interface{}, PacketLoader) error
	PacketsForEachUnAck([]byte, interface{}, PacketLoader) error
	PacketsStore([]byte, PersistedPackets) error
	//PacketsStoreUnAck([]byte, PersistedPackets) error
	PacketsDelete([]byte) error
	MsgStore(string, *mqttp.Publish)
	ConnectionStore(string, string, string, string)
}
```
and add a line in clients/session.go:
```
func (s *session) SignalPublish(pkt *mqttp.Publish) error {
	// fmt.Println("client session signalpublish: ", s.id, ", with qos: ", pkt.QoS(), ", with content: ", string(pkt.Payload()), ", on topic: ", pkt.Topic())
	pkt.SetPublishID(s.subscriber.Hash())
	s.persistence.MsgStore(s.username, pkt)

	// [MQTT-3.3.1.3]
	if pkt.Retain() {
```

then you can do your thing in your persistence plugin.

**Comment by troian** [comment]
All messages already persisted if session is non clean and connection is off. What is this for?

**Comment by xurwxj** [comment]
all messages lost when volantmq restarted, i need to keep all to search.
and i have not found persisted messages when session is non clean and connection is off.

**Comment by troian** [comment]
Surely it is as by default volantmq uses in-memory persistence provider.
There is boltd plugin allows to persist all messages into NoSQL database
Take a look examples/config.yaml:L27. Just uncomment 3 lines and set file value to place where you want db file to be stored
```
#    persistence:            # plugin type
#      - backend: bbolt      # plugin internal name
#        config:
#          file: "/usr/lib/volantmq/persistence/data/bbolt.db"
```

**Comment by xurwxj** [comment]
PacketsStore([]byte, PersistedPackets) error
 is this func to persist all messages?

**Comment by troian** [comment]
Yes, but you don't need to invoke it. It's volantmq job to persist messages if session meets requirements. So just enable boltd persistence plugin

**Comment by xurwxj** [comment]
i want to use redis to replace bolt when in production after experiment

**Comment by troian** [comment]
You need to implement redis plugin then
Take a look boltd example here
https://github.com/VolantMQ/vlapi/tree/master/plugin/persistence/bbolt

**Comment by xurwxj** [comment]
how to debug plugin source code with volantmq?
