### ISSUE TITLE
it does not work and it always gets none of retained message, because The Topic Name in the PUBLISH packet MUST NOT contain wildcard characters [MQTT-3.3.2-2]

### ISSUE THREAD

**Issue by hawklin2017** [VolantMQ/volantmq#87]
https://github.com/VolantMQ/volantmq/blob/a2f91245cb595e7754ecea0d3b3a775e58d9e6ee/topics/mem/node.go#L240

**Comment by troian** [comment]
Retained messages searched by subscription topic which may contain wildcards

**Comment by troian** [comment]
Closing as issue has wrong description.
