### ISSUE TITLE
Session panics when encountering errors

### ISSUE THREAD

**Issue by mochi-co** [VolantMQ/volantmq#88]
When any error occurs in clients/session.go, the library panics because the logger hasn't been instantiated.

> goroutine 21 [running]:
> go.uber.org/zap.(*Logger).check(0x0, 0x2, 0x463d310, 0x1f, 0xc42105f4c0)
> 	/Users/mochi/Development/Go/src/go.uber.org/zap/logger.go:266 +0xfd
> go.uber.org/zap.(*Logger).Error(0x0, 0x463d310, 0x1f, 0xc42105f4c0, 0x1, 0x1)
> 	/Users/mochi/Development/Go/src/go.uber.org/zap/logger.go:202 +0x44
> github.com/VolantMQ/volantmq/clients.(*session).SignalUnSubscribe(0xc4200a4000, 0xc4212b87e0, 0xc420febcd7, 0xc420018432, 0x1, 0xc420febd50)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/clients/session.go:234 +0x34e
> github.com/VolantMQ/volantmq/connection.(*impl).processIncoming(0xc420098500, 0x4945760, 0xc4212b87e0, 0xc4212b87e0, 0x0)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/connection/connection.go:633 +0x437
> github.com/VolantMQ/volantmq/connection.(*impl).rxRoutine(0xc420098500)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/connection/receiver.go:59 +0x24b
> github.com/VolantMQ/volantmq/connection.(*impl).rxRun.func1(0xc420098500)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/connection/receiver.go:22 +0x5e
> created by github.com/VolantMQ/volantmq/connection.(*impl).rxRun
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/connection/receiver.go:19 +0x9d
> exit status 2

It appears that when a newSession is created from the session manager, no instance of Zap logger is transferred from the manager.

The problem can be resolved by adding ` ses.log = m.log ` to sessions.go:434, however since I don't know enough about the current and planned architecture for VolantMQ I haven't issued a request. Maybe @troian can advise? 

(fantastic work on all this, by the way).

> func (m *Manager) allocContainer(id string, createdAt time.Time, cn connection.Session) *container {
> 	ses := newSession(sessionPreConfig{
> 		id:          id,
> 		createdAt:   createdAt,
> 		conn:        cn,
> 		messenger:   m.TopicsMgr,
> 		persistence: m.persistence,
> 	})
> 
> 	wrap := &container{}
> 	ses.idLock = &wrap.lock
>     ses.log = m.log // <-- :434 transfer manager logger to session
> 	wrap.ses.Store(ses)
> 	wrap.acquire()
> 
> 	return wrap
> }

**Comment by troian** [comment]
Thanks for reporting.
Fixed in the last master
