### ISSUE TITLE
"Panic: not implemented"; when client connects using CertFile and KeyFile.

### ISSUE THREAD

**Issue by mochi-co** [VolantMQ/volantmq#90]
If config.CertFile and config.KeyFile are set when starting the broker, the broker will panic with the message "not implemented" when a client attempts to connect.

> panic: not implemented
> 
> goroutine 7 [running]:
> github.com/troian/easygo/netpoll.Must(0x0, 0x4933940, 0xc420202560, 0x4933940)
> 	/Users/mochi/Development/Go/src/github.com/troian/easygo/netpoll/handle.go:46 +0x54
> github.com/VolantMQ/volantmq/connection.(*impl).Accept(0xc42018a000, 0xd, 0xd, 0x493d380)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/connection/connection.go:295 +0x9a
> github.com/VolantMQ/volantmq/clients.(*Manager).Handle(0xc42024e1e0, 0x5909060, 0xc4200da4e0, 0x4933980, 0xc4201ffd80, 0x45a5240, 0xc42002df01)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/clients/sessions.go:233 +0x388
> github.com/VolantMQ/volantmq/transport.(*baseConfig).handleConnection(0xc420230000, 0x493e880, 0xc4200da4e0)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/transport/base.go:85 +0x97
> github.com/VolantMQ/volantmq/transport.(*tcp).Serve.func1(0xc420230000, 0x493e7c0, 0xc420680380)
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/transport/tcp.go:134 +0xf4
> created by github.com/VolantMQ/volantmq/transport.(*tcp).Serve
> 	/Users/mochi/Development/Go/src/github.com/VolantMQ/volantmq/transport/tcp.go:128 +0xd3
> exit status 2
>

**Comment by troian** [comment]
Closing as stale
