### ISSUE TITLE
Auth Manager methods do nothing

### ISSUE THREAD

**Issue by mochi-co** [VolantMQ/volantmq#91]
I've been trying to implement the internal auth methods demonstrated in the examples folder, only I have discovered that neither my implementation nor the examples actually perform any checks - the auth manager Password method does not appear to be called during the connection establishment. I noticed in clients/sessions (processConnect) there's a lot of code commented out that seems to be related to the auth checks. 

Is there a plan for when this might return? I am happy to take a look at it if someone (@troian ?) wants to point me in the right direction for what needs doing. Sorry if I missed something! Many thanks for you work.

**Comment by troian** [comment]
I'm about to push API changes to auth stuff with some examples

**Comment by troian** [comment]
You can find updated API.
The main goal is VolamtMQ is not responsible for auth at all (there is basic auth included but it's recommended for demo purpose only).
Any kind of auth is not performed by plugins. I.e. it's planned to implement plugins for a different kind of authn/authz.
