### ISSUE TITLE
Add current examples?

### ISSUE THREAD

**Issue by disconsented** [VolantMQ/volantmq#98]

**Comment by troian** [comment]
Refer here 
https://github.com/VolantMQ/volantmq#how-to-use

**Comment by disconsented** [comment]
Sorry, I mean't a code example of how the server is intended to run rather than just running it on its own

**Comment by troian** [comment]
I see, well for quick reference you can take a look at main.go

**Comment by DrAuYueng** [comment]
how about the client example, any cases?

**Comment by DrAuYueng** [comment]
just like cmd ping.

**Comment by troian** [comment]
You can use MQTT.fx as test client.
